<div id="lspd_login_popup">
    <div id="lspd_login_wrapper">    
        <?php echo $this->getLayout()->createBlock('loginspeedup/form_login')
            ->setTemplate('persistent/customer/form/login.phtml')
            ->toHtml(); 
        ?>
        
    </div>
</div>

<script>
function showLoginDialog() {
    var loginPopup = new Window({
        className:'magento',
        width:700,
        height:500,
        minimizable:false,
        maximizable:false,
        draggable: false,
        showEffectOptions:{duration:0.4},
        hideEffectOptions:{duration:0.4}
    });
    loginPopup.setZIndex(100);
    loginPopup.showCenter(true);

    loginPopup.setContent('lspd_login_wrapper', false, true)

    loginPopup.show();
    return false;
}

function updateHandleToLogin(selector) {    
    $$(selector).each(function(button) {
        button.onclick = undefined;
        button.on('click', showLoginDialog)    
    });    
}

document.observe("dom:loaded", function() { 
    <?php $selectors = $this->getSelectors(); ?>
    <?php foreach ($selectors as $selector): ?>
        updateHandleToLogin("<?php echo $selector ?>");
    <?php endforeach; ?>    
});
</script>

